server:
  port: 8099
spring:
  application:
    name: configclient
eureka:
  instance:
    prefer-ip-address: true

student:
  name: zhangsan
  age: 20


      
      
      
      
      
      
      
      
