server:
  port: 8099
spring:
  application:
    name: configclient
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
student:
  name: zhangsan
  age: 15


      
      
      
      
      
      
      
      
