server:
  port: 8099
spring:
  application:
    name: configclient
  rabbitmq:
    host: 192.168.3.17
eureka:
  instance:
    prefer-ip-address: true

student:
  name: zhangsan
  age: 26


      
      
      
      
      
      
      
      
